export enum QueryKeys {
  messages = 'messages',
  sharedMessages = 'sharedMessages',
  sharedLinks = 'sharedLinks',
  allConversations = 'allConversations',
  archivedConversations = 'archivedConversations',
  searchConversations = 'searchConversations',
  conversation = 'conversation',
  searchEnabled = 'searchEnabled',
  user = 'user',
  authContexts = 'authContexts',
  organizations = 'organizations',
  organization = 'organization',
  organizationBilling = 'organizationBilling',
  backboardOrgs = 'backboardOrgs',
  backboardOrgBilling = 'backboardOrgBilling',
  analytics = 'analytics',
  name = 'name', // user key name
  models = 'models',
  balance = 'balance',
  plans = 'plans',
  subscription = 'subscription',
  billing = 'billing',
  endpoints = 'endpoints',
  presets = 'presets',
  searchResults = 'searchResults',
  tokenCount = 'tokenCount',
  availablePlugins = 'availablePlugins',
  startupConfig = 'startupConfig',
  assistants = 'assistants',
  assistant = 'assistant',
  agents = 'agents',
  agent = 'agent',
  files = 'files',
  filesUsage = 'filesUsage',
  fileConfig = 'fileConfig',
  tools = 'tools',
  toolAuth = 'toolAuth',
  toolCalls = 'toolCalls',
  mcpTools = 'mcpTools',
  mcpConnectionStatus = 'mcpConnectionStatus',
  mcpAuthValues = 'mcpAuthValues',
  agentTools = 'agentTools',
  actions = 'actions',
  assistantDocs = 'assistantDocs',
  agentDocs = 'agentDocs',
  fileDownload = 'fileDownload',
  voices = 'voices',
  customConfigSpeech = 'customConfigSpeech',
  prompts = 'prompts',
  prompt = 'prompt',
  promptGroups = 'promptGroups',
  allPromptGroups = 'allPromptGroups',
  promptGroup = 'promptGroup',
  categories = 'categories',
  randomPrompts = 'randomPrompts',
  agentCategories = 'agentCategories',
  marketplaceAgents = 'marketplaceAgents',
  roles = 'roles',
  conversationTags = 'conversationTags',
  health = 'health',
  userTerms = 'userTerms',
  chatAssistant = 'chatAssistant',
  banner = 'banner',
  /* Memories */
  memories = 'memories',
  principalSearch = 'principalSearch',
  accessRoles = 'accessRoles',
  resourcePermissions = 'resourcePermissions',
  effectivePermissions = 'effectivePermissions',
  graphToken = 'graphToken',
  /* MCP Servers */
  mcpServers = 'mcpServers',
  mcpServer = 'mcpServer',
  /* Active Jobs */
  activeJobs = 'activeJobs',
  /* Agent API Keys */
  agentApiKeys = 'agentApiKeys',
  /* Folders */
  folders = 'folders',
  /* Saved responses */
  savedMessages = 'savedMessages',
  savedMessageFolders = 'savedMessageFolders',
  /* Billing */
  billingSubscription = 'billingSubscription',
  referrals = 'referrals',
  /* Admin */
  adminUsers = 'adminUsers',
  adminUserSubscription = 'adminUserSubscription',
  adminPromoCodes = 'adminPromoCodes',
}

// Dynamic query keys that require parameters
export const DynamicQueryKeys = {
  agentFiles: (agentId: string) => ['agentFiles', agentId] as const,
} as const;

export enum MutationKeys {
  createAgentApiKey = 'createAgentApiKey',
  deleteAgentApiKey = 'deleteAgentApiKey',
  fileUpload = 'fileUpload',
  fileDelete = 'fileDelete',
  updatePreset = 'updatePreset',
  deletePreset = 'deletePreset',
  loginUser = 'loginUser',
  logoutUser = 'logoutUser',
  switchAuthContext = 'switchAuthContext',
  createOrganization = 'createOrganization',
  createOrganizationInvite = 'createOrganizationInvite',
  acceptOrganizationInvitation = 'acceptOrganizationInvitation',
  updateOrganizationMemberRole = 'updateOrganizationMemberRole',
  updateOrganizationMemberCreditLimit = 'updateOrganizationMemberCreditLimit',
  removeOrganizationMember = 'removeOrganizationMember',
  deleteOrganization = 'deleteOrganization',
  refreshToken = 'refreshToken',
  avatarUpload = 'avatarUpload',
  speechToText = 'speechToText',
  textToSpeech = 'textToSpeech',
  assistantAvatarUpload = 'assistantAvatarUpload',
  agentAvatarUpload = 'agentAvatarUpload',
  updateAction = 'updateAction',
  updateAgentAction = 'updateAgentAction',
  deleteAction = 'deleteAction',
  deleteAgentAction = 'deleteAgentAction',
  revertAgentVersion = 'revertAgentVersion',
  deleteUser = 'deleteUser',
  updateRole = 'updateRole',
  enableTwoFactor = 'enableTwoFactor',
  verifyTwoFactor = 'verifyTwoFactor',
  updateMemoryPreferences = 'updateMemoryPreferences',
  createFolder = 'createFolder',
  deleteFolder = 'deleteFolder',
  moveConvoToFolder = 'moveConvoToFolder',
  saveMessage = 'saveMessage',
  unsaveMessage = 'unsaveMessage',
  updateSavedMessage = 'updateSavedMessage',
  createSavedMessageFolder = 'createSavedMessageFolder',
  updateSavedMessageFolder = 'updateSavedMessageFolder',
  deleteSavedMessageFolder = 'deleteSavedMessageFolder',
}
